version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    volumes:
      - /home/pi/docker/home_assistant:/config
      - /home/pi/media:/media
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB-zigbee
      - /dev/ttyUSB-zwave
    environment:
      - TZ=America/Detroit
    restart: unless-stopped
    network_mode: host
