version: "3"
services:
  rtl_433:
    container_name: rtl_433
    image: rtl_433
    devices:
      - /dev/bus/usb/001/003
    restart: unless-stopped
    environment:
      - MQTT_USER=ha_broker
      - MQTT_PASSWORD=C0nn3ctM3!
      - MQTT_IP=192.168.86.62
